username = ENV['VAGRANT_CLOUD_USERNAME'] || mrbarker

Vagrant.configure("2") do |config|
    config.vm.box = username + "/ubuntu-amd64"
    config.vm.provider :vmware_desktop do |vmware|
      vmware.vmx["ethernet0.pcislotnumber"] = "33"
    end

    config.vm.provision "file", source: "flag.txt", destination: "/home/vagrant/flag.txt"
    config.vm.provision "shell", path: "bootstrap.sh"
end
